name: electis
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.2
  iconsax: ^0.0.8
  carousel_slider: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
          style: normal

        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
          style: normal

        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
          style: normal

        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
          style: normal

        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
          style: normal

        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
          style: normal

        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
          style: normal

        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
          style: normal

        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
          style: normal

