on:
    pull_request:
      branches:
        - main
    push:
      branches:
        - main
        - develop
name: "Build & Release"
jobs:
    build:
      name: Build & Release
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '11'
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            architecture: x64
  
        - run: flutter build apk --release --split-per-abi
        - name: Push to Releases
          uses: softprops/action-gh-release@v1
          with:
            artifacts: "build/app/outputs/apk/release/*"
            tag: v1.0.${{ github.run_number }}
            token: ${{ env.RELEASE_TOKEN }} 