name: Build & Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: softprops/action-gh-release@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.0
          token: ${{ secrets.RELEASE_TOKEN }}
